# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
        - "*"
    tags:
      - v*
  pull_request:
    branches: ["release", "main"]

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  TSA_IMAGE_NAME: tsa
  TSA_LOADER_IMAGE_NAME: tsa-loader
  TSA_TEST_TAG: bzhtux/tsa:test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mod:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v4
      - run: go mod tidy && git diff --exit-code go.mod go.sum
  test:
    needs: mod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.21']
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v4
    - run: go install github.com/onsi/ginkgo/v2/ginkgo
    - run: go get github.com/onsi/gomega/...
    - run: go vet ./...
    - run: ginkgo run -p ./... -bench=./... -vv
  build_loader:
    needs: [mod, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          load: false
          file: Dockerfile.loader
  build_tsa:
    needs: [mod, test, build_loader]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: install goss and dgoss to test docker images
        run: curl -fsSL https://goss.rocks/install | sh
      - name: build for test
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: Dockerfile.app
          tags: ${{ env.TSA_TEST_TAG }}
  test_tsa_image:
    needs: [mod, test, build_tsa]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: install goss and dgoss to test docker images
        run: curl -fsSL https://goss.rocks/install | sh
      - name: test with dgoss
        run: dgoss run ${{ env.TSA_TEST_TAG }}