# This is a basic workflow to help you get started with Actions

name: build_docker_images

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [unit_testing]
    types:
      - completed
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
        - "*"
    tags:
      - v*
  pull_request:
    branches: ["main", "release"]
  

env:
  REGISTRY: ghcr.io
  TSA_IMAGE_NAME: tsa
  TSA_LOADER_IMAGE_NAME: tsa-loader
  TSA_TEST_TAG: bzhtux/tsa:test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_loader:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: pwd
      - run: ls -l
      - uses: docker/build-push-action@v5
        with:
          context: .
          load: false
          file: Dockerfile.loader
  build_tsa:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: build_loader
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: install goss and dgoss to test docker images
        run: curl -fsSL https://goss.rocks/install | sh
      - name: build for test
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: Dockerfile.app
          tags: ${{ env.TSA_TEST_TAG }}
